version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: whatsapp-ha:latest
    ports:
      - 3000:3000
    volumes:
      - .wwebjs_auth:/data
      - .:/app

    environment:
      # - SUPERVISOR_TOKEN=token
      # - HA_BASE_URL=https://localhost:8123
      - LOG_LEVEL=debug
      - TZ=America/Guayaquil

  npm:
    image: whatsapp-ha:latest
    volumes:
      - .:/app
      - .wwebjs_auth:/data
    working_dir: /app
    entrypoint: npm
    
